### ISSUE TITLE
Fix authorization on nova routes

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-impersonator#14]

**Comment by herroworrd** [comment]
https://github.com/GeneaLabs/laravel-impersonator/blob/737677fe673cccfa506062b0c05f3336e134c56a/src/Providers/Tool.php#L24

This line breaks your package for those not using Nova.

**Comment by mikebronner** [comment]
@herroworrd Thanks for reporting this.
Can you provide more details as to what is breaking, and what you think the fix might be? (I'm currently using it in Nova without issue.)

**Comment by herroworrd** [comment]
Probably just a simple test using class_exists would suffice.

class_exists('Laravel\Nova\Nova')

Re: what is breaking...

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Laravel\Nova\Nova' not found

**Comment by mikebronner** [comment]
Oh, I misread ... I missed the "not" in "not using Nova". Gotcha, thanks! this should have been filed as a separate issue. I moved it over to its own issue.

**Comment by mikebronner** [comment]
Closing this for now until the original issue re-emerges.
