### ISSUE TITLE
Breaks in projects that don't use Nova.

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-impersonator#15]
https://github.com/GeneaLabs/laravel-impersonator/blob/737677fe673cccfa506062b0c05f3336e134c56a/src/Providers/Tool.php#L24

This line breaks your package for those not using Nova.

_Originally posted by @herroworrd in https://github.com/GeneaLabs/laravel-impersonator/issues/14#issuecomment-504117299_

**Comment by mikebronner** [comment]
@herroworrd This should now be fixed in release 0.3.2. Let me know how it works. (I tested it in a vanilla Laravel project, and it loaded without errors.)

**Comment by herroworrd** [comment]
Hi Mike, Works now. Thanks for making this change.

**Comment by mikebronner** [comment]
@herroworrd Awesome, thanks for reporting the issue. :)
