### ISSUE TITLE
genealabs/laravel-impersonator 0.1.2 requires illuminate/routing 5.4.*

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-impersonator#2]
The impersonator can't be installed with newest Laravel version which use illuminate/routing > 5.4:
![impersonator](https://user-images.githubusercontent.com/27913135/34460931-b333e52a-ee1d-11e7-8a78-c33ef51f77eb.JPG)

**Comment by mikebronner** [comment]
Thanks, will fix ASAP
