### ISSUE TITLE
Publishing of config files failes

### ISSUE THREAD

**Issue by Nowi5** [GeneaLabs/laravel-impersonator#7]
# Issue
No new config file is published when run artisan:

> php artisan impersonator:publish --config
> Publishing complete.

## Environment
Laravel Version: 5.5
Laravel Impersonator Package Version: 0.2.0
PHP Version: 7

**Comment by mikebronner** [comment]
Working on this now - hope to have them all sorted in a few hours. This was due to a change I made in version 0.2.0. Adding tests to cover that issue.
